name: Golang ChatApp CI/CD
on:
  push:
    branches: [$default_branch]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      # - name: Build application
      #   run: go build -o chatapp ./cmd/chatapp

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: chatapp-binary