name: Golang ChatApp CI/CD
on:
  push:
    branches: [$default_branch]
  pull_request:
    # types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
    
  code-review:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Before AutoReviewer
        run: echo "About to run AutoReviewer"
      - uses: gvasilei/AutoReviewer@0.5.1
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      - name: After AutoReviewer
        run: echo "Finished AutoReviewer"
          # exclude_files: '*.json'   # optionally exclude files
      # - name: Build application
      #   run: go build -o chatapp ./cmd/chatapp

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: chatapp-binary