name: Golang ChatApp CI/CD
on:
  push:
    branches: [$default_branch]
  pull_request:
    # types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
    
  code-review:
    runs-on: ubuntu-latest
    # if: ${{ contains( github.event.label.name, 'AutoReview') }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: sshnaidm/gpt-code-review-action@v2.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}


      # - name: Build application
      #   run: go build -o chatapp ./cmd/chatapp

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: chatapp-binary